import { GUIDE_ANCHORS as A } from "./catalog";
import { createCurriculum } from "./curriculumFactory";

const err = (message) => [message];
const lesson = (module, anchor, title, instruction, output, error, extra = {}) => ({
  module,
  anchor,
  openView: module,
  title,
  instruction,
  output,
  commonErrors: err(error),
  ...extra,
});

const routes = [
  {
    id: "included-data-first-analysis",
    module: "analysis",
    title: "Survival analysis: from question to result",
    summary: "Learn how to plan and interpret a survival analysis. The guide leaves your current settings unchanged.",
    prerequisites: [],
    objectives: [
      "Declare population, marker, endpoint and contrast before running.",
      "Treat the continuous model as primary evidence and grouping as support.",
    ],
    nextGuideId: "groups-to-pathways",
    lessons: [
      lesson("home", A.HOME_OVERVIEW, "Frame the question", "Write who you will study, which marker and outcome you will use, and what effect you want to estimate.", "A question defined before viewing the results.", "Choosing an analysis because of the desired plot."),
      lesson("summary", A.DATASET_COVERAGE, "Check eligibility", "Review patients, RNA samples, endpoints, events and clinical coverage.", "A viable cohort and endpoint with recorded limitations.", "Assuming a large cohort always has enough events."),
      lesson("analysis", A.SURVIVAL_DATASET, "Configure the design", "Work through Data, Marker design, Outcome, Patient filters and adjustment and Review. At each stage, make the choice that matches your own question; the guide does not change any control for you.", "A visible, editable analysis design with no result yet.", "Running before the full question and analysis population are clear."),
      lesson("analysis", A.SURVIVAL_RESULTS, "Read primary evidence", "Start with the continuous HR and confidence interval; use KM and groups to communicate time patterns.", "Direction, magnitude, uncertainty and effective population.", "Reporting a high-versus-low HR as though it described a continuous increase in expression."),
      lesson("analysis", A.SURVIVAL_DIAGNOSTICS, "Check the model", "Review events per parameter, PH diagnostics, penalized sensitivity and unavailable outputs.", "An interpretation that accounts for the model checks.", "Ignoring diagnostics because the coefficient is large."),
      lesson("analysis", A.SURVIVAL_OUTCOME, "Error lab", "Change one decision, predict its consequence, then compare without selecting the favorable result.", "An explanation of how that choice changed the result, labeled as exploratory.", "Presenting exploratory sensitivity as confirmation."),
      lesson("analysis", A.SURVIVAL_DOWNLOADS, "Export and connect", "Download tables, methodology and the run record with the question and limitations.", "An auditable review package.", "Saving only a figure."),
    ],
  },
  {
    id: "own-data",
    module: "analysis",
    title: "Analyze your own data",
    summary: "Prepare your files, match patients and use custom variables in gene and pathway analyses.",
    prerequisites: ["De-identified expression and outcome files.", "Permission to upload and analyze de-identified data."],
    objectives: [
      "Validate the patient × expression × outcome links before analysis.",
      "Check custom variables and identify which file errors need correction before you can run.",
    ],
    nextGuideId: "groups-to-pathways",
    lessons: [
      lesson("analysis", A.SURVIVAL_UPLOAD, "Protect and prepare", "Confirm that files are de-identified and keep original copies outside the temporary session.", "An inventory of files, units and patient keys.", "Using names or direct clinical identifiers as keys.", { presetId: "own-data-upload-start" }),
      lesson("analysis", A.SURVIVAL_UPLOAD_EXPRESSION, "Validate expression", "Check matrix orientation, gene symbols, numeric values, duplicates and one prioritized sample per patient.", "A normalized matrix with explained dimensions and duplicates.", "Declaring counts as TPM or treating samples as patients."),
      lesson("analysis", A.SURVIVAL_UPLOAD_OUTCOME, "Validate outcomes", "Map ID, time, event, unit and time origin; inspect negative times, impossible events and duplicates.", "An endpoint with unambiguous censoring and units.", "Mixing days and months or reversing event and censoring."),
      lesson("analysis", A.SURVIVAL_UPLOAD_METADATA, "Map metadata", "Classify categorical and numeric variables; review levels, coverage and timing before grouping or filtering.", "Usable clinical variables with their sources and missing values recorded.", "Automatically adjusting for every uploaded column."),
      lesson("expression", A.EXPRESSION_GROUPS, "Test custom groups", "Build two groups from an eligible variable and verify disjoint levels, counts and exclusions.", "A traceable contrast and descriptive expression comparison.", "Treating sparse or missing levels as interpretable groups.", { presetId: "own-data-clinical-groups" }),
      lesson("gsea", A.GSEA_COLLECTION, "Test pathways in the same groups", "Reuse the contrast, choose GO or another collection, and declare the set sizes and descriptive NES ranking.", "CAMERA p/FDR plus bidirectional NES, leading edge and a downloadable ranking.", "Calling pathway association direct causal activation.", { presetId: "own-data-gsea-go" }),
      lesson("gsea", A.GSEA_RESULTS, "Error lab and final package", "Safely exercise an unmatched ID, an ineligible variable and a circular contrast; document each correction.", "Blocking errors, cautions and an audit package without sensitive data.", "Fixing an error by hiding patients or changing the hypothesis."),
    ],
  },
  {
    id: "groups-to-pathways",
    module: "expression",
    title: "From groups to pathways",
    summary: "Define one contrast, compare genes, then interpret GSEA in the same direction.",
    prerequisites: ["An eligible cohort and a two-group hypothesis.", "Basic FDR concepts."],
    objectives: ["Keep A/B assignments stable across modules.", "Separate CAMERA evidence from NES direction and leading edge."],
    nextGuideId: "robustness-multiplicity",
    lessons: [
      lesson("expression", A.EXPRESSION_DATASET, "Declare the contrast", "Define the population, reference group A, target group B and biological rationale before selecting genes.", "An unambiguous B minus A contrast.", "Naming groups without declaring the reference."),
      lesson("expression", A.EXPRESSION_GROUPS, "Check eligibility", "Use TCGA-BRCA stage as the primary contrast; reserve expression-derived PAM50 for explicitly labeled exploration.", "Two disjoint groups with visible provenance.", "Combining levels after looking at expression.", { presetId: "groups-brca-stage" }),
      lesson("expression", A.EXPRESSION_GENES, "Choose genes", "Choose a small gene panel that addresses your question. Check that none of the tested genes defines the groups.", "An explicit family of up to 25 tests.", "Using adaptively selected genes without disclosure.", { presetId: "groups-expression-panel" }),
      lesson("expression", A.EXPRESSION_RESULTS, "Interpret distributions", "Read B minus A, dispersion, Welch and Mann-Whitney; use violin, boxplot and heatmap as complementary views.", "Magnitude, direction, FDR and agreement between tests.", "Comparing heatmap color magnitude across genes."),
      lesson("gsea", A.GSEA_GROUPS, "Transfer the groups", "Recreate the exact A/B assignment in GSEA and verify the B minus A ranking direction.", "A GSEA contrast linked to expression analysis.", "Reversing A/B during transfer.", { presetId: "groups-gsea-go" }),
      lesson("gsea", A.GSEA_RESULTS, "Read the DotPlot and leading edge", "Read position and color as descriptive NES, point area as min(−log10 CAMERA FDR, 10), and inspect residual correlation, direction agreement, leading-edge genes and GO redundancy. The complete table remains downloadable.", "Prioritized pathways with correlation-aware evidence, direction and contributing genes.", "Counting redundant GO terms as independent replication."),
      lesson("gsea", A.GSEA_GROUPS, "Separate PAM50 exploration", "Contrast Luminal A and Basal-like only as exploratory because PAM50 is expression-derived; do not merge it with the primary stage contrast.", "A PAM50 hypothesis labeled exploratory plus the primary-analysis package.", "Treating expression-derived PAM50 as independent clinical evidence.", { presetId: "groups-brca-pam50-exploratory" }),
    ],
  },
  {
    id: "robustness-multiplicity",
    module: "compare",
    title: "Robustness and multiplicity",
    summary: "Learn what Compare, planned Robustness analyses and run history each tell you.",
    prerequisites: ["A completed survival analysis.", "Basic HR and interval interpretation."],
    objectives: ["Use the continuous model as the reference.", "Keep the testing families and interpretation of Compare, Robustness and Run history separate."],
    nextGuideId: "validation-generalization",
    lessons: [
      lesson("analysis", A.SURVIVAL_RESULTS, "Fix the continuous reference", "Record the continuous direction, HR and uncertainty before testing groups.", "A cutpoint-independent reference.", "Starting with maxstat and omitting the continuous result."),
      lesson("compare", A.COMPARE_METHODS, "Declare the comparison", "Use PDCD1 in TCGA-SKCM and select cutpoints as one family while holding endpoint and adjustment fixed.", "A planned gene × cutpoint matrix.", "Adding methods after seeing a favorable cell.", { presetId: "compare-skcm-pdcd1-cutpoints" }),
      lesson("compare", A.COMPARE_RESULTS, "Assess stability", "Compare direction, magnitude, precision and exclusions against the continuous reference.", "A comparison of all planned results, including uncertainty and disagreement.", "Reporting only the smallest p value."),
      lesson("multiverse", A.MULTIVERSE_DESIGN, "Plan the Robustness analysis", "Use CDC20 in TCGA-LIHC and declare endpoint × scoring × cutpoint plus eligibility rules before execution.", "An auditable family of known size.", "Calling retrospective runs a prespecified family.", { presetId: "multiverse-lihc-cdc20" }),
      lesson("multiverse", A.MULTIVERSE_RESULTS, "Read the curve", "Interpret effect distribution, intervals, unavailable specifications and continuous versus grouped families.", "Robustness across plausible decisions.", "Choosing a primary analysis after seeing which result looks best."),
      lesson("session", A.SESSION_LEDGER, "Contrast with history", "Compare recorded runs with the analysis plan and identify choices made after viewing results.", "A clear boundary between prospective and retrospective work.", "Using history as a substitute for prespecification."),
      lesson("session", A.SESSION_LEDGER, "Export the family", "Export the analysis record, methods and all results, including failures and unfavorable analyses.", "A multiplicity record without silent selection.", "Reporting only completed or significant specifications."),
    ],
  },
  {
    id: "validation-generalization",
    module: "repository",
    title: "Validation and generalization",
    summary: "Move from an independent cohort to pan-cancer synthesis and programmatic reproduction.",
    prerequisites: ["A defined hypothesis, outcome and effect unit in the starting cohort.", "Basic heterogeneity concepts."],
    objectives: ["Check that the new cohort can test the same question.", "Interpret combined study estimates while keeping their expression matrices and patients separate."],
    nextGuideId: null,
    lessons: [
      lesson("repository", A.REPOSITORY_FINDER, "Declare validation", "Fix marker, endpoint, direction and success criterion before searching for a cohort.", "A validation protocol independent of catalog results.", "Choosing a cohort because it supports the expected result."),
      lesson("repository", A.REPOSITORY_PROVENANCE, "Audit compatibility", "Review publication, platform, scale, patients, events, endpoint, covariates, license and provenance.", "A justified include, exclude or exploratory decision.", "Assuming endpoint names imply identical time definitions."),
      lesson("analysis", A.SURVIVAL_RESULTS, "Run an individual validation", "Analyze the external cohort separately with the fixed design and retain adjustment limitations.", "Independent-study effect, interval and diagnostics.", "Pooling external data with TCGA before estimating study effects."),
      lesson("pancancer", A.PANCANCER_QUERY, "Scan TCGA", "Estimate CDC20 effects by cancer with a common scale, minimum information and declared FDR.", "Forest, concordance, evidence and precision by cancer.", "Treating the global estimate as universal.", { presetId: "pancancer-cdc20-tcga" }),
      lesson("pancancer", A.PANCANCER_PREFLIGHT, "Check studies for synthesis", "Review the CDC20 studies grouped by cancer. Check outcomes, scale, patient overlap, timing and exclusions before combining estimates.", "A recorded eligibility check with its version.", "Ignoring dependence by study or cancer.", { presetId: "pancancer-hierarchical-cdc20" }),
      lesson("pancancer", A.PANCANCER_RESULTS, "Interpret heterogeneity", "Read study and cancer effects, global synthesis, heterogeneity, modified-HKSJ status, prediction interval, leave-one-out influence, sensitivity analyses and unavailable-study reasons.", "An interpretation of where the association holds, on which scale and with how much variation.", "Confusing no evidence with evidence of no effect.", { scientificContractId: "pancancer.hierarchical" }),
      lesson("api", A.API_REST, "Reproduce and hand off", "Export results and methods; reproduce a public query through API or MCP with a fixed version and no identifiers.", "A machine-readable validation package.", "Treating assistant prose as evidence without checking artifacts."),
    ],
  },
];

const quick = (definition) => definition;
const guideStep = ({ error, ...step }) => ({
  ...step,
  commonErrors: err(error),
});

const quickGuides = [
  quick({
    module: "home",
    title: "Home, section by section",
    summary: "Find the right analysis and understand what the available data can support.",
    prerequisites: [],
    objectives: [
      "Choose a section from your scientific question.",
      "Know what information should accompany a result.",
      "Separate available data from evidence produced by an analysis.",
    ],
    steps: [
      guideStep({
        id: "orientation", title: "1. Overview", anchor: A.HOME_OVERVIEW,
        why: "The overview shows what data are available, not how many patients will enter a specific analysis.",
        instruction: "Read the coverage figures, then write down the population, marker, endpoint and purpose of your question.",
        output: "A focused question linked to available data.",
        error: "Using Home totals as the sample size of a later analysis.",
      }),
      guideStep({
        id: "workspace", title: "2. Choose an analysis", anchor: A.HOME_WORKSPACE,
        why: "Each section answers a different kind of question.",
        instruction: "Choose Survival for time-to-event questions, Expression for gene differences, GSEA for pathways, Compare or Robustness for analysis choices, and Pan-cancer for evidence across cancers or studies.",
        output: "The section that matches your question.",
        error: "Choosing a workflow because its plot looks familiar.",
      }),
      guideStep({
        id: "foundation", title: "3. Save the analysis settings", anchor: A.HOME_FOUNDATION,
        why: "A result can be checked only when its data and choices are recorded.",
        instruction: "Record the dataset release, patient unit, expression scale, endpoint and analysis version.",
        output: "The data version and settings needed to reproduce an analysis.",
        error: "Saving a figure without the data version and settings that produced it.",
      }),
      guideStep({
        id: "interpret", title: "4. How to use Home", anchor: A.HOME_INTERPRETATION,
        why: "Home helps you navigate; it does not provide biological evidence.",
        instruction: "Move to the selected section and verify eligible patients, missing data and any analysis-specific requirements there.",
        output: "An analysis section to continue in.",
        error: "Interpreting catalog availability as evidence for an association.",
      }),
    ],
  }),
  quick({
    module: "analysis",
    title: "Survival analysis, step by step",
    summary: "Set up a survival analysis in five stages, then interpret the result.",
    prerequisites: [],
    estimatedMinutes: 7,
    objectives: [
      "Make each setup decision in order.",
      "Read the effect, uncertainty and diagnostics together.",
      "Keep the continuous result separate from grouped supporting views.",
    ],
    steps: [
      {
        id: "data", title: "1. Data", anchor: A.SURVIVAL_DATASET, workspaceStepId: "data",
        why: "The dataset defines the patients and the meaning of the expression values.",
        instruction: "Choose a cohort or upload your data. Check the release, patient count, RNA samples and expression scale.",
        output: "A dataset with a known population and expression scale.",
        commonErrors: err("Treating every RNA sample as an independent patient."),
        cannotConclude: ["A large dataset does not guarantee enough events or a biological association."],
      },
      {
        id: "marker", title: "2. Marker", anchor: A.SURVIVAL_MARKER, workspaceStepId: "design",
        why: "The marker is the molecular signal you want to test.",
        instruction: "Choose a gene, signature, interaction or panel, and confirm how its score is calculated.",
        output: "A clearly defined molecular marker.",
        commonErrors: err("Changing the marker after seeing a result."),
        cannotConclude: ["Selecting a marker does not establish mechanism or causality."],
      },
      {
        id: "outcome", title: "3. Outcome", anchor: A.SURVIVAL_OUTCOME, workspaceStepId: "outcome",
        why: "The outcome defines the event and follow-up being studied.",
        instruction: "Choose the endpoint and confirm its event, time origin, patient count and event count. If needed, choose a grouping rule for the grouped Kaplan-Meier view.",
        output: "A defined endpoint and an optional grouping rule.",
        commonErrors: err("Treating a grouped curve as the primary test of a continuous marker."),
        cannotConclude: ["An outcome-optimized cutpoint is exploratory; cause-specific Cox and Fine-Gray answer different questions."],
      },
      {
        id: "clinical", title: "4. Patient filters and adjustment", anchor: A.SURVIVAL_CLINICAL, workspaceStepId: "clinical",
        why: "Filters define who is analyzed; covariates define the adjusted comparison.",
        instruction: "Apply only justified clinical filters and covariates, then check how missing values change the adjusted sample.",
        output: "A defined population and adjustment plan.",
        commonErrors: err("Assuming adjustment restores excluded or missing patients."),
        cannotConclude: ["Adjustment does not remove all confounding or make the result causal."],
      },
      {
        id: "review-run", title: "5. Review and run", anchor: A.SURVIVAL_REVIEW, workspaceStepId: "review",
        why: "A final check prevents a mismatch between your question and the analysis.",
        instruction: "Review the population, marker, endpoint, continuous effect, grouping, filters and adjustment, then run the analysis.",
        output: "A reviewed analysis ready to run.",
        commonErrors: err("Running first and defining the question afterward."),
        cannotConclude: ["One fitted model is not independent validation; plot styling does not change the evidence."],
      },
      {
        id: "interpret", title: "6. How to read the result", anchor: A.SURVIVAL_RESULTS,
        why: "Patient counts and model assumptions help determine how much confidence to place in the estimated effect.",
        instruction: "Read patients and events first; then the continuous HR and 95% CI; then proportional-hazards and functional-form checks; finally the grouped views, warnings and downloads. HR above 1 means higher instantaneous hazard as the marker increases; HR below 1 means lower hazard.",
        output: "A brief interpretation with population, effect, uncertainty and one limitation.",
        commonErrors: err("Summarizing the analysis with the p value or grouped curve alone."),
        cannotConclude: ["A hazard ratio is not an absolute survival difference or death probability, and association is not causation."],
      },
    ],
  }),
  quick({
    module: "compare", title: "Compare, step by step", summary: "Compare planned survival analyses and judge whether the result is stable.", prerequisites: [],
    objectives: ["Define all comparisons before running them.", "Interpret the full pattern, not one favorable result."],
    steps: [
      guideStep({ id: "dataset", title: "1. Dataset", anchor: A.COMPARE_DATASET, workspaceStepId: "dataset",
        why: "All comparisons need the same data foundation.",
        instruction: "Confirm the cohort, release, endpoint and expression scale shared by the analyses.",
        output: "One common dataset for all comparisons.", error: "Comparing results without noticing that the patient populations differ." }),
      guideStep({ id: "markers", title: "2. Markers", anchor: A.COMPARE_MARKERS, workspaceStepId: "markers",
        why: "The marker list defines what will be compared.",
        instruction: "Choose the planned genes or signatures and confirm how each score is built and directed.",
        output: "A fixed marker list.", error: "Adding markers after seeing earlier results." }),
      guideStep({ id: "methods", title: "3. Grouping methods", anchor: A.COMPARE_METHODS, workspaceStepId: "methods",
        why: "Different cutpoints can assign patients to different groups.",
        instruction: "Choose the planned grouping rules and keep the continuous model as the reference when available.",
        output: "A fixed set of grouping methods.", error: "Choosing the cutpoint with the smallest p value." }),
      guideStep({ id: "clinical", title: "4. Patient filters and adjustment", anchor: A.COMPARE_CLINICAL, workspaceStepId: "filters",
        why: "Clinical choices can change the population and the adjusted effect.",
        instruction: "Use the same justified filters and covariates across all comparisons.",
        output: "One clinical design for all analyses.", error: "Comparing analyses that use different clinical rules." }),
      guideStep({ id: "review-run", title: "5. Review and run", anchor: A.COMPARE_REVIEW, workspaceStepId: "run",
        why: "The complete set should be fixed before results are visible.",
        instruction: "Review the dataset, markers, methods, clinical rules and total comparison count. If the Cox forest should show only particular adjusted models, choose those rows before running.",
        output: "A reviewed set of planned comparisons.", error: "Expanding the comparison set after inspecting results." }),
      guideStep({ id: "interpret", title: "6. How to read the result", anchor: A.COMPARE_RESULTS,
        why: "Robustness is shown by the pattern across all comparisons.",
        instruction: "Compare effect direction, magnitude, 95% CI, patient count and availability. Interpret BH and Bonferroni across the full set, and compare grouped results with the continuous model.",
        output: "A conclusion describing stable, uncertain and discordant results.", error: "Reporting only the smallest p value.",
        requirements: [{ id: "compare.resultAvailable", capability: "compare.resultAvailable", blocking: true, jumpWhenAvailable: true }] }),
    ],
  }),
  quick({
    module: "expression", title: "Expression comparison, step by step", summary: "Compare one or more genes between two clearly defined groups.", prerequisites: [],
    objectives: ["Define Group A and Group B clearly.", "Read statistics and expression plots together."],
    steps: [
      guideStep({ id: "dataset", title: "1. Dataset", anchor: A.EXPRESSION_DATASET,
        why: "The dataset defines the patients and expression measurements.",
        instruction: "Choose the cohort and confirm the release, expression layer, scale and patient-level sample rule.",
        output: "A dataset with a known population and scale.", error: "Treating RNA samples as independent patients." }),
      guideStep({ id: "genes", title: "2. Genes", anchor: A.EXPRESSION_GENES,
        why: "The gene list defines the expression comparisons.",
        instruction: "Search for and select the planned genes, then confirm their symbols. Do not test a gene as independent evidence if it helped define the groups.",
        output: "A fixed list of valid genes.", error: "Testing a group-defining gene as independent evidence." }),
      guideStep({ id: "groups", title: "3. Groups", anchor: A.EXPRESSION_GROUPS,
        why: "Group A and Group B define the comparison direction.",
        instruction: "Create two non-overlapping groups from clinical data, a survival split or gene expression. Check their origin, size, missing values and exclusions. Results use B minus A.",
        output: "Two traceable groups with a clear direction.", error: "Relabeling groups after inspecting expression." }),
      guideStep({ id: "test-family", title: "4. Test family", anchor: A.EXPRESSION_TEST_FAMILY,
        why: "Welch and Mann-Whitney compare different features of the distributions.",
        instruction: "Choose Welch for mean differences or Mann-Whitney for rank-distribution differences. Apply BH FDR across the selected genes for each method.",
        output: "A preselected test and correction method.", error: "Choosing a different test for each gene by its p value." }),
      guideStep({ id: "interpret", title: "5. How to read the result", anchor: A.EXPRESSION_RESULTS,
        why: "Statistics and plots show complementary parts of the difference.",
        instruction: "Read B minus A, group sizes, effect size and BH FDR. Use violins for distribution shape, boxplots for summaries and outliers, and the heatmap for patient patterns after scaling each gene.",
        output: "A gene-wise conclusion with direction, size and uncertainty.", error: "Reading heatmap colors as raw expression across different genes." }),
    ],
  }),
  quick({
    module: "gsea", title: "GSEA, step by step", summary: "Rank genes between two groups and identify enriched biological programs.", prerequisites: [],
    objectives: ["Keep the B minus A direction clear.", "Separate CAMERA evidence from NES and leading-edge genes."],
    steps: [
      guideStep({ id: "dataset", title: "1. Dataset", anchor: A.GSEA_DATASET,
        why: "The dataset defines the patients and genes used for ranking.",
        instruction: "Choose the cohort and confirm the release, expression scale and patient-level sample rule.",
        output: "One expression dataset for grouping and ranking.", error: "Creating groups and rankings from different dataset versions." }),
      guideStep({ id: "groups", title: "2. Groups", anchor: A.GSEA_GROUPS,
        why: "The group order determines the sign of the ranking and NES.",
        instruction: "Define two non-overlapping groups and check their size, exclusions and origin. Ranking uses B minus A: positive values favor B; negative values favor A.",
        output: "Two groups with a fixed comparison direction.", error: "Reversing A and B during interpretation." }),
      guideStep({ id: "collection", title: "3. Gene sets and ranking", anchor: A.GSEA_COLLECTION,
        why: "The collection and ranking settings determine which pathways are tested.",
        instruction: "Choose a gene-set collection, including GO when appropriate, and set the gene-set limits. Ranking, permutations and seed define descriptive NES; CAMERA supplies correlation-aware p-values.",
        output: "A fixed collection and reproducible ranking setup.", error: "Changing collections after seeing the enriched pathways." }),
      guideStep({ id: "interpret", title: "4. How to read the result", anchor: A.GSEA_RESULTS,
        why: "Direction, adjusted evidence and contributing genes answer different questions.",
        instruction: "Use DotPlot color for NES and dot size for -log10 FDR. Then read the exact FDR, set size and leading-edge genes in the table. Similar GO terms may describe overlapping biology.",
        output: "A pathway conclusion with direction, FDR and leading-edge genes.", error: "Calling enrichment proof of pathway activation or causality." }),
    ],
  }),
  quick({
    module: "multiverse", title: "Robustness, step by step", summary: "Test whether a result changes across several defensible analysis choices.", prerequisites: [],
    objectives: ["Define all choices before running them.", "Separate effect changes from uncertainty and failed models."],
    steps: [
      guideStep({ id: "dataset", title: "1. Dataset", anchor: A.MULTIVERSE_DATASET, workspaceStepId: "dataset",
        why: "Every analysis needs the same data foundation.",
        instruction: "Confirm the cohort, release, expression layer and patient-level sample rule.",
        output: "One dataset for every analysis.", error: "Combining analyses built from incompatible data." }),
      guideStep({ id: "marker", title: "2. Marker", anchor: A.MULTIVERSE_MARKER, workspaceStepId: "marker",
        why: "The marker defines the molecular question being tested.",
        instruction: "Choose the gene or signature and confirm how its score and direction are defined.",
        output: "One stable marker definition.", error: "Changing marker construction without listing it as a planned choice." }),
      guideStep({ id: "decisions", title: "3. Analysis choices", anchor: A.MULTIVERSE_DESIGN, workspaceStepId: "decisions",
        why: "Only scientifically reasonable choices should enter the Robustness analysis.",
        instruction: "Select the planned endpoints, scoring methods, cutpoints and other decisions, and check the resulting analysis count.",
        output: "A planned set of analysis choices with a reason for each.", error: "Adding choices because earlier results were unfavorable." }),
      guideStep({ id: "clinical", title: "4. Patient filters and adjustment", anchor: A.MULTIVERSE_CLINICAL, workspaceStepId: "clinical",
        why: "Clinical choices can change the analyzed patients and adjusted effect.",
        instruction: "Select justified filters and adjustment options, and note which choices reduce the eligible sample.",
        output: "A clear set of clinical choices.", error: "Treating every available covariate as equally appropriate." }),
      guideStep({ id: "review-run", title: "5. Review and run", anchor: A.MULTIVERSE_REVIEW, workspaceStepId: "run",
        why: "All planned analyses should be fixed before results are visible.",
        instruction: "Review every choice, the total count and eligibility rules, then run all analyses together and keep failures visible.",
        output: "A reviewed Robustness analysis ready to run.", error: "Removing analyses expected to fail or look unfavorable." }),
      guideStep({ id: "interpret", title: "6. How to read the result", anchor: A.MULTIVERSE_RESULTS,
        why: "Robustness comes from the complete pattern, including failed analyses.",
        instruction: "Read effect direction, magnitude, 95% CI, patient count and availability across the curve. Distinguish a changed effect from wider uncertainty or a changed population.",
        output: "An interpretation of how results change across the planned analyses, including failures.", error: "Selecting one favorable analysis as the answer.",
        requirements: [{ id: "multiverse.resultAvailable", capability: "multiverse.resultAvailable", blocking: true, jumpWhenAvailable: true }] }),
    ],
  }),
  quick({
    module: "session", title: "Run history, step by step", summary: "Review what was analyzed, in what order and with which settings.", prerequisites: [],
    objectives: ["Keep a clear record of the session.", "Separate comparable runs from later exploration."],
    steps: [
      guideStep({ id: "setup", title: "1. Session record", anchor: A.SESSION_SETUP,
        why: "A clear label makes the analysis history easier to understand.",
        instruction: "Name the session and state its purpose. Remember that the record stays in this browser and is not preregistration.",
        output: "A labeled local session record.", error: "Treating browser history as a registered analysis plan." }),
      guideStep({ id: "ledger", title: "2. Recorded runs", anchor: A.SESSION_LEDGER,
        why: "Settings and status show which runs answer the same question.",
        instruction: "Compare the module, dataset, endpoint, marker, reference, scale, status, warnings and time for every run. Keep failures and unfavorable results.",
        output: "A complete chronological record with comparable runs identified.", error: "Combining runs only because they use the same gene." }),
      guideStep({ id: "interpret", title: "3. How to read Run history", anchor: A.SESSION_INTERPRETATION,
        why: "Run history documents exploration; it does not make it prospective.",
        instruction: "Report the full sequence as post hoc and export it. Use Robustness when choices must be fixed before execution.",
        output: "A record of the analyses tried and when they were run.", error: "Calling a favorable subset a prespecified robustness analysis.",
        requirements: [{ id: "session.runsAvailable", capability: "session.runsAvailable", blocking: true, jumpWhenAvailable: true }] }),
    ],
  }),
  quick({
    module: "pancancer", title: "Pan-cancer, step by step", summary: "Compare evidence across cancers or studies without pooling their patients.", prerequisites: [],
    scientificContractId: "pancancer.mode_aware",
    objectives: ["Keep study and cancer as separate levels.", "Choose between TCGA reference and hierarchical synthesis."],
    steps: [
      guideStep({ id: "mode", title: "1. Choose an analysis", anchor: A.PANCANCER_MODE,
        why: "The two modes answer different cross-cancer questions.",
        instruction: "Choose Across TCGA cancer types to compare a gene or signature between cancer types. Choose Across independent studies to examine one gene in several cohorts, using overall survival. Each cohort keeps its own model and patients.",
        output: "A mode matched to the question.", error: "Mixing effect scales from the two modes." }),
      guideStep({ id: "design", title: "2. Analysis design", anchor: A.PANCANCER_QUERY,
        why: "The marker, endpoint and information rules define what can be compared.",
        instruction: "For TCGA cancer types, choose a gene or signature and the survival outcome. For independent studies, choose one gene and the cohorts to include; overall survival is fixed. Minimum patient and event counts determine which cancers or studies can enter.",
        output: "A defined pan-cancer analysis.", error: "Treating cancers or studies as interchangeable patient batches." }),
      guideStep({ id: "eligibility", title: "3. Check eligibility", anchor: A.PANCANCER_PREFLIGHT,
        requirements: [],
        why: "Eligibility must be checked before combining evidence.",
        instruction: "Review patient and event counts, endpoint compatibility, study independence, sample overlap, effect scale and every exclusion.",
        output: "A list of eligible studies, exclusions and missing results.", error: "Excluding evidence because its direction is unfavorable." }),
      guideStep({ id: "interpret", title: "4. How to read the result", anchor: A.PANCANCER_RESULTS,
        why: "A global estimate does not mean the effect is identical everywhere.",
        instruction: "Read study effects and 95% CIs first, then cancer summaries, heterogeneity, prediction interval, influence and unavailable results. Name the effect scale. Treat the precomputed Immune atlas as a separate hypothesis screen, not independent replication.",
        output: "An interpretation that names the studies, cancers, effect scale and variation between estimates.", error: "Calling a combined association universal or causal." }),
    ],
  }),
];

function fixedExample({
  id,
  module,
  anchor,
  title,
  summary,
  sourceLabel,
  theme,
  evidence,
  evidenceConclusion,
  error,
  scientificContractId,
}) {
  const subject = (instruction, output, commonError) => ({ instruction, output, commonErrors: err(commonError) });
  return {
    id, module, anchor, title, summary, sourceLabel, scientificContractId,
    prerequisites: ["Basic interpretation of the named output."],
    objectives: [theme],
    context: subject("Read the fixed question, population and endpoint.", "The question, patients and outcome used in the example.", "Treating the case as a result from the current analysis."),
    design: subject("Identify the effect, reference, test family and assumptions.", "A reconstructed analysis design.", "Inferring design from a favorable panel."),
    evidence: subject(
      `Interpret ${evidence}.`,
      evidenceConclusion,
      error,
    ),
    transfer: subject("Describe how you would use this method for a new question. Its numerical results will depend on your data.", "A plan to try in your own analysis.", "Expecting the same numerical result."),
  };
}

const examples = [
  fixedExample({ id: "example-continuous-before-cutpoint", module: "examples", anchor: A.EXAMPLES_CATALOG, title: "Continuous before cutpoint", summary: "Read the continuous effect first, then use the grouped curves as a sensitivity analysis.", sourceLabel: "Versioned synthetic teaching case", theme: "Avoid cutpoint selection.", evidence: "continuous HR, interval, KM and PH diagnostics", evidenceConclusion: "The +1 SD continuous Cox result is an instantaneous-hazard association; it is neither excess deaths nor a causal effect, and the grouped display remains a cutpoint-based sensitivity view.", error: "Reading only the grouped curve.", scientificContractId: "survival.continuous" }),
  fixedExample({ id: "example-private-data-error-lab", module: "analysis", anchor: A.SURVIVAL_UPLOAD, title: "Private-data error lab", summary: "Problematic IDs, units and metadata in a safe fixture.", sourceLabel: "De-identified synthetic fixture", theme: "Classify blocking and repairable errors.", evidence: "unmatched IDs, unit conflicts, sparse metadata and post-treatment variables", evidenceConclusion: "Duplicate IDs and an invalid scale block import; unmatched IDs may be repairable, while time units, measurement timing and Cox covariate use require semantic review.", error: "Automatically adjusting for every metadata column.", scientificContractId: "dataset.eligibility" }),
  fixedExample({ id: "example-gsea-direction", module: "gsea", anchor: A.GSEA_RESULTS, title: "Direction in GSEA", summary: "Read NES, FDR, DotPlot area and leading edge.", sourceLabel: "Versioned synthetic teaching case", theme: "Preserve B minus A.", evidence: "NES direction, the full FDR family, capped top-30 point area, leading-edge genes and redundant GO terms", evidenceConclusion: "Positive NES points toward Group B and negative NES toward Group A under B minus A; neither direction establishes activation or causality.", error: "Calling enrichment measured causal activation.", scientificContractId: "gsea.preranked" }),
  fixedExample({ id: "example-multiplicity-boundaries", module: "multiverse", anchor: A.MULTIVERSE_RESULTS, title: "Multiplicity boundaries", summary: "Separate Compare, Robustness and run history.", sourceLabel: "Versioned synthetic teaching case", theme: "Distinguish prospective and post hoc families.", evidence: "the robustness curve, failures and complete ledger", evidenceConclusion: "Compare and Robustness are declared families; run history is explicitly post hoc, and failed or unfavorable specifications remain in the ledger.", error: "Excluding unfavorable or unavailable specifications.", scientificContractId: "multiverse.specification_family" }),
  fixedExample({ id: "example-pancancer-heterogeneity", module: "pancancer", anchor: A.PANCANCER_RESULTS, title: "Pan-cancer heterogeneity", summary: "Concordant, discordant and imprecise study effects.", sourceLabel: "Versioned synthetic teaching case", theme: "Do not confuse global with universal.", evidence: "study and cancer effects, intervals, heterogeneity and the prediction interval", evidenceConclusion: "The imprecise global estimate and prediction interval spanning both sides of HR 1 do not support a universal direction across cancers or studies.", error: "Counting effect signs without intervals.", scientificContractId: "pancancer.hierarchical" }),
];

const manuals = [
  {
    id: "manual-data-contracts", title: "Prepare and upload data", summary: "What TRACE needs from your files, how patients are matched, and what to review before analysis.",
    sections: [
      { id: "population-unit", title: "Start with the patient", paragraphs: ["TRACE analyzes patients, not files or aliquots. Use one patient key across files. If a patient has more than one RNA sample, choose one with a rule you can explain and apply consistently."], checklist: ["Report patient and sample counts separately.", "Document how duplicate samples were resolved."] },
      { id: "file-contract", title: "Provide the essential columns", paragraphs: ["Expression data need gene symbols, numeric values and the correct expression scale. Patient metadata need matching patient IDs. For survival analysis, also supply follow-up time, event status and the time unit, and state when follow-up starts and what event = 1 means. Expression and GSEA do not require a survival outcome."], checklist: ["Remove names and other direct identifiers.", "Use one time unit throughout the file.", "Check the event and censoring codes."] },
      { id: "metadata", title: "Review clinical variables", paragraphs: ["Tell TRACE whether each variable is numeric or categorical. Check how many patients have data and whether the groups are large enough. Variables measured after treatment, derived from the outcome or derived from expression need special interpretation and are not added to Cox models automatically."], checklist: ["Keep the original variable names and levels.", "Make missing and rare levels visible.", "Mark PAM50 and similar labels as expression-derived."] },
      { id: "error-lab", title: "Fix problems without changing the question", paragraphs: ["IDs that do not match are a linkage problem. A variable with one usable level cannot define a comparison. A gene should not both create the groups and be tested as independent evidence. Correct the data problem, but do not quietly redefine groups or remove inconvenient patients."], checklist: ["Review every blocker, caution and exclusion.", "Keep an untouched copy of the source files.", "Export only de-identified results."] },
    ],
  },
  {
    id: "manual-survival-robustness", title: "Survival and robustness", summary: "How to read survival estimates, diagnostics and repeated analyses without selecting only the most favorable result.",
    sections: [
      { id: "estimand", title: "Start with the continuous effect", paragraphs: ["The continuous Cox model is the cutpoint-independent reference. It estimates how the hazard changes for a one standard-deviation increase in the marker among the patients included in that model. A grouped model answers a related question based on the selected cutpoint."], checklist: ["State the marker unit and analysis population.", "Report the hazard ratio with its confidence interval.", "Describe an association, not a causal effect."] },
      { id: "diagnostics", title: "Check whether the model is reliable", paragraphs: ["Read event counts, uncertainty and proportional-hazards diagnostics together. TRACE may show Firth or RMST sensitivity results when they are informative. If a result cannot be estimated, the reason should remain visible."], checklist: ["Review marker and global diagnostics.", "Use cautious language when information is limited.", "Keep failed or unavailable results in the record."] },
      { id: "compare", title: "Compare choices without choosing a winner", paragraphs: ["Compare changes genes or cutpoints while keeping the rest of the design fixed. Look for stable direction, magnitude and patient inclusion. Do not select one analysis only because it has the smallest p-value."], checklist: ["Declare the comparisons before running them.", "Report every planned result.", "Check that direction and populations remain comparable."] },
      { id: "multiverse-history", title: "Define the analysis family before looking", paragraphs: ["Robustness evaluates a declared set of reasonable analytical choices. Decisions added after seeing results are exploratory and must be labeled that way. Planned and exploratory analyses should not share one inferential claim."], checklist: ["Record when each decision was made.", "Keep incompatible testing families separate.", "Export the complete set of specifications."] },
    ],
  },
  {
    id: "manual-groups-pathways", title: "Groups, expression and GSEA", summary: "How to carry one clear group comparison from gene expression to pathway enrichment.",
    sections: [
      { id: "contrast", title: "Make the comparison explicit", paragraphs: ["Group A is the reference and Group B is the target. TRACE reports B minus A, so every effect needs to be read in that direction. The groups must not overlap, and missing or excluded patients should remain visible."], checklist: ["Give the B minus A contrast a biological meaning.", "Review group sizes and missing data.", "Use the same patient definition across modules."] },
      { id: "expression", title: "Compare genes without hiding the distributions", paragraphs: ["Read the effect size and corrected p-values together. TRACE runs both tests: Welch compares means, and Mann-Whitney compares ranked distributions. Each has a separate multiple-testing correction. Violin and boxplots show distributions; the heatmap shows patterns after scaling each gene."], checklist: ["Inspect effect direction, uncertainty and dispersion.", "Do not compare heatmap colors between different genes.", "Report all genes in the declared panel."] },
      { id: "gsea", title: "Read evidence and direction separately", paragraphs: ["CAMERA tests whether each set is unusually differential after estimating its residual gene correlation. NES then shows where that set concentrates in the B minus A ranking. In the DotPlot, color and position show NES, while dot area shows −log10 CAMERA FDR, capped at 10. The full table contains the complete tested family."], checklist: ["Record the collection and group definition.", "Check whether CAMERA and NES directions agree.", "Inspect leading-edge genes and treat overlapping GO terms as related, not independent findings."] },
      { id: "circularity", title: "Keep group definitions independent", paragraphs: ["Do not use a gene to define the groups and then present the test of that same gene as independent evidence. Expression-derived labels such as PAM50 can be biologically useful, but comparisons based on them should be identified as expression-derived and interpreted carefully."], checklist: ["Compare grouping genes with the tested gene list.", "Separate exploration from independent validation.", "Test new leading-edge hypotheses in new data."] },
    ],
  },
  {
    id: "manual-validation-generalization", title: "Validation and pan-cancer", summary: "How to test a result in another cohort and combine evidence without treating every study as the same population.",
    sections: [
      { id: "validation-protocol", title: "Define validation before searching", paragraphs: ["Fix the marker, endpoint, effect scale, expected direction and success criterion before looking through external cohorts. Validation should test a question that was already defined."], checklist: ["Preserve the same quantity being estimated.", "Set eligibility rules in advance.", "Confirm that the validation study is independent."] },
      { id: "compatibility", title: "Check whether cohorts answer the same question", paragraphs: ["Compare platform, normalization, endpoint definition, start of follow-up, covariates, patients, events, license and data origin. Two variables can have the same name and still mean different things."], checklist: ["Record every difference from the index cohort.", "Analyze each study separately.", "Do not pool raw expression matrices across studies."] },
      { id: "hierarchy", title: "Analyze each study separately", paragraphs: ["TRACE estimates an effect in each study, combines compatible studies of the same cancer, then summarizes effects across cancers. Before combining results, it checks eligibility, patient overlap and exclusions."], checklist: ["Keep study, cancer and global levels visible.", "Resolve overlapping patient populations.", "Retain unavailable studies and their reasons."] },
      { id: "heterogeneity", title: "Interpret variation before the average", paragraphs: ["A global estimate is not a universal biological effect. Read cancer-specific intervals, heterogeneity and the prediction interval before the pooled estimate. Then inspect leave-one-out and sensitivity analyses to see whether one study or assumption drives the conclusion."], checklist: ["Do not call a global estimate universal.", "Separate disagreement from imprecision.", "State where the result may not generalize."] },
    ],
  },
  {
    id: "manual-reproducibility", title: "Save, reproduce and report", summary: "What another researcher needs to understand, check and reproduce your analysis.",
    sections: [
      { id: "minimum-record", title: "Save the decisions", paragraphs: ["Keep the software version, dataset release, cohort, endpoint, expression scale, reference group, filters, marker, testing family and every exclusion reason. These choices define the result."], checklist: ["Store parameters and versions together.", "Include unfavorable and unavailable results.", "Exclude sensitive information from exports."] },
      { id: "downloads", title: "Export more than the figure", paragraphs: ["A figure cannot reproduce an analysis by itself. Export the result table, plotting data, methods and, when relevant, rankings, assignments and the analysis record."], checklist: ["Keep readable and machine-readable formats.", "Retain release identifiers or hashes.", "Preserve cautions and exclusions."] },
      { id: "api", title: "Reproduce through API or MCP", paragraphs: ["Begin with a known public analysis. Send explicit parameters, use a fixed API version and compare the returned settings with the interface. Interface coverage can differ, so verify the returned artifacts rather than relying on assistant text."], checklist: ["Never send sensitive identifiers.", "Keep partial failures visible.", "Check generated explanations against the data."] },
      { id: "report", title: "Write a result another scientist can evaluate", paragraphs: ["Report the question, population, estimated effect, uncertainty, multiple-testing approach, diagnostics, limitations and whether the analysis was planned or exploratory."], checklist: ["Report independently of statistical significance.", "Use associative rather than causal language.", "Label the next analysis as a new hypothesis."] },
    ],
  },
];

export const curriculumEn = createCurriculum({
  lang: "en",
  labels: {
    learningCenter: "Learn TRACE",
    guides: "Tutorials",
    examples: "Examples",
    manuals: "Manuals",
    routes: "Learning routes",
    quickGuides: "Quick guides",
    liveGuide: "Current analysis",
    fixedExample: "Fixed example",
    prerequisites: "Before you start",
    objectives: "Objectives",
    overview: "Before you start",
    estimatedTime: "Estimated time",
    minutes: "min",
    why: "Why this matters",
    cannotConclude: "Limits of interpretation",
    concepts: "Terms used here",
    references: "Methods and references",
    operationalPitfalls: "Setup problems",
    inferentialPitfalls: "Interpretation pitfalls",
    completeGuide: "Complete guide",
    reviewGuide: "Review guide",
    minimize: "Minimize tutorial",
    expand: "Expand tutorial",
    unavailable: "Not available with your current choices",
    requirements: "Result availability",
    sourceKind: "Evidence source",
    sourceKinds: {
      live: "Current analysis",
      synthetic_case: "Synthetic teaching case",
      computed_benchmark: "Computed benchmark",
    },
    recommendedContinuation: "Next guide",
    output: "What you should see",
    commonErrors: "Common errors",
    step: "Step",
    of: "of",
    start: "Start",
    resume: "Resume",
    previous: "Previous",
    next: "Next",
    finish: "Finish",
    close: "Close tutorial",
    openModule: "Open module",
    applyPreset: "Apply preset",
    presetApplied: "Preset applied; review every decision before running.",
    progress: "Tutorial progress",
    printManual: "Save guide as PDF",
    manualContents: "Choose a topic",
    manualGuide: "Practical guide",
    manualChecks: "What to check",
    manualConcepts: "Terms used in this guide",
    manualReferences: "Scientific references",
    provenance: "Example data source",
    resultId: "Teaching content ID",
    pipelineVersion: "Analysis version",
    snapshotDate: "Snapshot",
    sha256: "SHA-256",
    verifyArtifact: "Open the example data",
  },
  phases: {
    question: "Question",
    eligibility: "Eligibility",
    design: "Design",
    "primary-evidence": "Primary evidence",
    diagnostics: "Diagnostics",
    "error-lab": "Error lab",
    handoff: "Save and continue",
  },
  common: {
    quickSteps: { orient: "What this section does", interpret: "How to read it", verify: "What to check" },
    exampleSteps: { context: "Context", design: "Design", evidence: "Evidence", transfer: "Transfer" },
  },
  routes,
  quickGuides,
  examples,
  manuals,
});

export default curriculumEn;
