#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = ROOT / "docs" / "publication" / "benchmark" / "data_snapshot_manifest.json"


def main() -> int:
    args = parse_args()
    manifest = build_manifest(args)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"Wrote {args.output}")
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Export a submission-facing manifest for the local TCGA snapshot used by TCGA-TRACE. "
            "Use --hash-count-matrices for the final submission manifest; without it, count matrices "
            "are size-pinned but not content-hashed to keep quick development checks fast."
        )
    )
    parser.add_argument("--tcga-data-dir", type=Path, default=ROOT.parent / "TCGA")
    parser.add_argument(
        "--rna-sync-manifest",
        type=Path,
        default=ROOT.parent / "TCGA" / ".sync" / "manifests" / "tcga_rna_current.json",
    )
    parser.add_argument("--cdr-file", type=Path, default=ROOT / "clinical" / "TCGA-CDR-SupplementalTableS1.xlsx")
    parser.add_argument("--cdr-manifest", type=Path, default=ROOT / "clinical" / ".sync" / "manifests" / "tcga_cdr_current.json")
    parser.add_argument("--cache-manifest", type=Path, default=ROOT / "derived" / "rna_bulk" / "startup_cache_manifest.json")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--hash-count-matrices", action="store_true")
    return parser.parse_args()


def build_manifest(args: argparse.Namespace) -> dict[str, Any]:
    tcga_dir = args.tcga_data_dir
    cohorts = sorted(path for path in tcga_dir.glob("TCGA-*") if path.is_dir())
    cohort_rows = [cohort_manifest(path, hash_count_matrix=args.hash_count_matrices) for path in cohorts]
    summary_table = tcga_dir / "summary_table.tsv"
    validation_table = tcga_dir / "tcga_validation_summary.tsv"
    payload = {
        "schema_version": "tcga-trace-data-snapshot-manifest-v1",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "tcga_data_dir": display_path(tcga_dir),
        "rna_snapshot": {
            "source_description": "Local TCGA cohort directories with count_matrix.tsv, col_data.tsv, clinical_data.tsv and dds.rds generated by the local download pipeline.",
            "hash_count_matrices": bool(args.hash_count_matrices),
            "cohort_count": len(cohort_rows),
            "cohorts": cohort_rows,
            "summary_table": file_record(summary_table, sha=True),
            "validation_table": file_record(validation_table, sha=True),
            "validation_summary": validation_summary(validation_table),
            "sync_manifest_file": file_record(args.rna_sync_manifest, sha=True),
            "sync_manifest": read_json(args.rna_sync_manifest),
        },
        "tcga_cdr": {
            "file": file_record(args.cdr_file, sha=True),
            "sync_manifest": read_json(args.cdr_manifest),
        },
        "derived_cache": {
            "startup_cache_manifest": read_json(args.cache_manifest),
        },
        "submission_note": (
            "For final journal submission, run this script with --hash-count-matrices. "
            "If the RNA snapshot was created by the application updater, include the "
            "GDC sync manifest with --rna-sync-manifest. Archive this manifest with "
            "the software release."
        ),
    }
    payload["manifest_hash"] = stable_hash(payload)
    return payload


def cohort_manifest(path: Path, *, hash_count_matrix: bool) -> dict[str, Any]:
    count_matrix = path / "count_matrix.tsv"
    return {
        "cohort": path.name,
        "count_matrix": file_record(count_matrix, sha=hash_count_matrix),
        "col_data": file_record(path / "col_data.tsv", sha=True),
        "clinical_data": file_record(path / "clinical_data.tsv", sha=True),
        "dds_rds": file_record(path / "dds.rds", sha=False),
    }


def validation_summary(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {"status": "missing"}
    with path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle, delimiter="\t"))
    return {
        "status": "available",
        "cohorts": len(rows),
        "passing_cohorts": sum(1 for row in rows if row.get("status") == "pass"),
        "failing_cohorts": [row.get("cohort") for row in rows if row.get("status") != "pass"],
    }


def file_record(path: Path, *, sha: bool) -> dict[str, Any]:
    if not path.exists():
        return {"path": display_path(path), "status": "missing", "sha256": None}
    stat = path.stat()
    return {
        "path": display_path(path),
        "status": "available",
        "bytes": stat.st_size,
        "mtime": datetime.fromtimestamp(stat.st_mtime, timezone.utc).isoformat(),
        "sha256": file_sha256(path) if sha else None,
        "sha256_status": "computed" if sha else "not_computed",
    }


def read_json(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def display_path(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT.parent.resolve()))
    except ValueError:
        return str(path)


def stable_hash(payload: dict[str, Any]) -> str:
    raw = json.dumps(stable_payload(payload), sort_keys=True, separators=(",", ":"), ensure_ascii=True)
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def stable_payload(value: Any) -> Any:
    if isinstance(value, dict):
        return {
            key: stable_payload(item)
            for key, item in value.items()
            if key not in {"generated_at", "mtime", "manifest_hash", "duration_seconds"}
        }
    if isinstance(value, list):
        return [stable_payload(item) for item in value]
    return value


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


if __name__ == "__main__":
    sys.exit(main())
